export enum Tag {
  anxiety,
  depression,
  stressManagement,
  griefAndLoss,
  addiction,
  codependency,
  selfEsteem,
  trauma,
  eatingDisorders,
  angerManagement,
  socialSkills,
  mindfulness,
  sexualAndGenderOrientation,
}
